version: '3.10'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-app
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lmsdb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
